
ln -s ../Python_Classes4MAD/madxrunner.py ./Analyses/madxrunner.py
ln -s /afs/cern.ch/user/a/amorita/public/mirror-ldata/LHC/SAD/BetaAnalysis.sad ./beta_Phase/SAD/BetaAnalysis.sad
ln -s /afs/cern.ch/user/a/amorita/public/mirror-ldata/LHC/SAD/BetaAnalysis.sad ./beta_Phase/JorgW/SPS/BetaAnalysis.sad
ln -s /nfs/cs-ccr-nfs4/lhc_data/OP_DATA/FILL_DATA/830 ./beta_Phase/JorgW/LHC/830
ln -s /nfs/cs-ccr-nfs4/lhc_data/OP_DATA/FILL_DATA/831 ./beta_Phase/JorgW/LHC/831
ln -s ./ ./Correction/Iterative/TEST/b1/filedes
ln -s /afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/ ./Correction/Iterative/TEST/b1/fileloc
ln -s ../LHCB/model/ ./MODEL/LHCB1/model
ln -s /afs/cern.ch/user/r/rtomas/w1/MAD/LHC/Beta-Beat/SimulateData/ ./MODEL/LHCB1/SimulateData
ln -s ../LHCB/fullresponse/ ./MODEL/LHCB1/fullresponse
ln -s ../LHCB/model/ ./MODEL/LHCB2/model
ln -s ../LHCB/fullresponse/ ./MODEL/LHCB2/fullresponse
ln -s /afs/cern.ch/user/r/rcalaga/mad/rhic ./MODEL/RHIC/ds/rhic
ln -s /afs/cern.ch/eng/lhc/optics/V6.503/ ./MODEL/LHCB/model/StrengthFiles/Nominal
ln -s /afs/cern.ch/eng/lhc/optics/ATS_V6.503/OPTICS_round_IR1_40-10_IR5_40-10/ ./MODEL/LHCB/model/StrengthFiles/ATS
ln -s ../Python_Classes4MAD/ ./Python_Classes4MAD
ln -s /afs/cern.ch/sw/IntelSoftware/linux/x86_64/Compiler/11.1/072/bin/intel64/ifort ./DRIVE_src.Massimo/ifort
ln -s /user/psbop/images/DODO-Export/ ./PSB_orbit_correction/DODO-Export
ln -s /user/psbop/data/2012/Q_meas/ ./PSB_orbit_correction/Q_meas
