2017-08-24#18-57-12:
Name: LhcModelCreation
Command:
ssh cs-ccr-optics1 /afs/cern.ch/work/o/omc/anaconda/bin/python /afs/cern.ch/eng/sl/lintrack/Beta-Beat.src//model/creator.py nominal --accel=lhc --lhcmode=lhc_runII_2017 --beam=1 --nattunex=0.31 --nattuney=0.318 --acd --drvtunex=0.298 --drvtuney=0.32799998 --dpp=0.0 --energy=0.45 --optics=/user/tpersson/BetaBeat/2017-08-24/models/LHCB1/40cm_Ac/modifiers.madx --fullresponse --output=/user/tpersson/BetaBeat/2017-08-24/models/LHCB1/40cm_Ac --writeto=/user/tpersson/BetaBeat/2017-08-24/models/LHCB1/40cm_Ac/job.twiss.madx --logfile=/user/tpersson/BetaBeat/2017-08-24/models/LHCB1/40cm_Ac/madx_log.txt

2017-08-24#18-57-33:
Name: GenerateFullResponse
Command:
ssh cs-ccr-optics1 /afs/cern.ch/work/o/omc/anaconda/bin/python /afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/MODEL/LHCB/fullresponse/generateFullResponse_parallel.py --accel=LHCB1 --path=/user/tpersson/BetaBeat/2017-08-24/models/LHCB1/40cm_Ac --core=/afs/cern.ch/eng/sl/lintrack/Beta-Beat.src/MODEL/LHCB/fullresponse --deltak=0.00002 --deltakl=0.0 -t

2017-08-24#18-58-04:
Errors: /afs/cern.ch/work/o/omc/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py:1776: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
/afs/cern.ch/work/o/omc/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py:1776: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
/afs/cern.ch/work/o/omc/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py:1776: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
/afs/cern.ch/work/o/omc/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py:1776: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
/afs/cern.ch/work/o/omc/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.py:1776: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)


