#!/bin/bash

# INPUT:
#  - 1: path to Beta-Beat.src
#  - 2: path to model
#  - 3: accelerator name
#  - 4: sdds file 1
#  - 5: sdds file 2
#  - 6: sdds file 3

# Environment:
# NUMDIFF variable should be set and point to the numdiff binary

# correct as long as we only use each model once..
base=`basename $2`

# use python2.6 if found, otherwise default..
[ -x /usr/bin/python2.6 ] && PYTHON=/usr/bin/python2.6 || PYTHON=/usr/bin/python
# use madx from afs if you don't have it in your path..
[ -x madx ] && MADX=madx || MADX=/afs/cern.ch/group/si/slap/bin/madx

$PYTHON $1/GetLLM/getsuper.py \
 --madxbin=$MADX \
 --twissfile="$2/twiss.dat" \
 --output=./out_${base}/ --algorithm=SUSSIX --accel=$3 \
 --beta=$1/ \
 "$4" \
 "$5" \
 "$6" \
  || exit 1


# check output files:

n_errs=0
n_files=0
for f in `ls $1/tests/${base}_out/*.out`
do
    fname=`basename $f`
    dname=`dirname $f`
    echo $NUMDIFF -b $f ./out_${base}/$fname ${dname}/default.cfg
    "$NUMDIFF" -b $f ./out_${base}/$fname ${dname}/default.cfg 2>&1 | tee tmp_ndiff.out
    # since numdiff returns 0 always,
    # we grep for warnings in the output..
    grep ^warng tmp_ndiff.out && n_errs=`expr $n_errs + 1`
    n_files=`expr $n_files + 1`
done

# if errors, print message
if (( $n_errs > 0 ))
then
    echo "$n_errs files of a total of $n_files differ"
fi
# exit value equals number of wrong files..
exit $n_errs
