#!/bin/bash

# INPUT:
#  - 1: path to sdds files

base=`basename $0`
dir=`dirname $0`

/usr/bin/python $1/GetLLM/getsuper_dev.py \
 --twiss="$1/tests/models/LHCB1/1_10_1_3/" \
 --output=out_${base}/ --algorithm=SUSSIX --accel=LHCB1 \
 --beta=$1/ \
 "$1/tests/sdds_files/Beam1@Turn@2011_08_24@08_21_27_607_0.sdds.new.gz" \
 "$1/tests/sdds_files/Beam1@Turn@2011_08_24@09_14_23_920_0.sdds.new.gz" \
 "$1/tests/sdds_files/Beam1@Turn@2011_08_24@09_40_52_536_0.sdds.new.gz" \
  || exit 1


# check output files:

for f in `ls $1/tests/${base}_out/*`
do
    fname=`basename $f`
    diff $f $dir/out_${base}/$fname || exit 1
done
