#!/bin/bash

# INPUT:
#  - 1: path to Beta-Beat.src

base=`basename $0`
NUMDIFF=/afs/cern.ch/eng/sl/lintrack/virtualenv-cs-ccr-optics1/bin/numdiff
# use python2.6 if found, otherwise default..
[ -x /usr/bin/python2.6 ] && PYTHON=/usr/bin/python2.6 || PYTHON=/usr/bin/python
# use madx from afs if you don't have it in your path..
[ -x madx ] && MADX=madx || MADX=/afs/cern.ch/group/si/slap/bin/madx

$PYTHON $1/GetLLM/getsuper.py \
 --madxbin=$MADX \
 --twissfile="$1/tests/models/LHCB1/1_10_1_3/twiss.dat" \
 --output=./out_${base}/ --algorithm=SUSSIX --accel=LHCB1 \
 --beta=$1/ \
 "$1/tests/sdds_files/Beam1@Turn@2011_08_24@08_21_27_607_0.sdds.new.gz" \
 "$1/tests/sdds_files/Beam1@Turn@2011_08_24@09_14_23_920_0.sdds.new.gz" \
 "$1/tests/sdds_files/Beam1@Turn@2011_08_24@09_40_52_536_0.sdds.new.gz" \
  || exit 1


# check output files:

n_errs=0
n_files=0
for f in `ls $1/tests/${base}_out/*.out`
do
    fname=`basename $f`
    dname=`dirname $f`
    echo $NUMDIFF -b $f ./out_${base}/$fname ${dname}/default.cfg
    $NUMDIFF -b $f ./out_${base}/$fname ${dname}/default.cfg 2>&1 | tee tmp_ndiff.out
    # since numdiff returns 0 always,
    # we grep for warnings in the output..
    grep ^warng tmp_ndiff.out && n_errs=`expr $n_errs + 1`
    n_files=`expr $n_files + 1`
done

# if errors, print message
if (( $n_errs > 0 ))
then
    echo "$n_errs files of a total of $n_files differ"
fi
# exit value equals number of wrong files..
exit $n_errs
