2015-07-09#10-48-26:
Name: GetLlm
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/GetLLM/GetLLM.py --accel=LHCB1 --model=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB1/model_injection_b1/twiss.dat --files=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB1/Measurements/Beam1@Turn@2015_04_10@23_46_40_802_0.new/Beam1@Turn@2015_04_10@23_46_40_802_0.sdds.new.new,/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB1/Measurements/Beam1@Turn@2015_04_10@23_50_53_298_0.new/Beam1@Turn@2015_04_10@23_50_53_298_0.sdds.new.new --output=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB1/Results/10-48-25_NORMALANALYSIS_SUSSIX_1 --tbtana=SUSSIX --bpmu=mm --lhcphase=1

2015-07-09#10-48-36:
Errors: Did not parse line ( "LHCB1$END" 23519.36962 10.98729506 -0.00111309785 11.0062402 0.0009082651555 56.47887532 52.31220228 -0.001161157975 0 -1.309301156e-05 0 0 0 0 0 0 0 16.34552929 16.12168727 112.8447423 106.3099844 1.092111048 2.844061501 "MARKER" 0 0 -0 0 -0 0 ) in  /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB1/model_injection_b1/twiss_elements.dat
Did not parse line ( "LHCB1$START" 23519.36962 10.98729506 -0.00111309785 11.0062402 0.0009082651555 56.47887532 52.31220228 -0.001161157975 0 -1.309301156e-05 0 0 0 0 0 0 0 16.34552929 16.12168727 112.8447423 106.3099844 1.092111048 2.844061501 "MARKER" 0 0 -0 0 -0 0 ) in  /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB1/model_injection_b1/twiss_elements.dat
WARNING: Cannot find bet_deviations.npy file!
WARNING: Cannot find bet_deviations.npy file!
WARNING: Cannot find bet_deviations.npy file!
WARNING: Cannot find bet_deviations.npy file!
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:67: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


2015-07-09#10-48-37:
Name: CorrectCoupleDy
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/Correction/correct_coupleDy.py --accel=LHCB1 --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB1/Results/10-48-25_NORMALANALYSIS_SUSSIX_1 --cut=0.01 --errorcut=0.02,0.02 --modelcut=0.0,0.01 --rpath=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/ --MinStr=0.000001 --Dy=1,1,0,0,0 --opt=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB1/model_injection_b1/ --Variables=coupling_knobs

2015-07-09#10-48-38:
Name: Madx
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/madx/madx_wrapper.py --file=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB1/Results/10-48-25_NORMALANALYSIS_SUSSIX_1/job.cor.madx

2015-07-09#10-48-42:
Name: GetDiff
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/MODEL/LHCB/model/Corrections/getdiff.py /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB1/Results/10-48-25_NORMALANALYSIS_SUSSIX_1

2015-07-09#10-48-42:
Name: GnuPlot
Command:
gnuplot /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB1/Results/10-48-25_NORMALANALYSIS_SUSSIX_1/gplot

