2015-07-09#11-01-28:
Name: GetLlm
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/GetLLM/GetLLM.py --accel=LHCB2 --model=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss.dat --files=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Measurements/Beam2@Turn@2015_04_10@23_33_41_516_0.new/Beam2@Turn@2015_04_10@23_33_41_516_0.sdds.new.new,/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Measurements/Beam2@Turn@2015_04_10@23_40_53_697_0.new/Beam2@Turn@2015_04_10@23_40_53_697_0.sdds.new.new --output=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --tbtana=SUSSIX --bpmu=mm --lhcphase=1

2015-07-09#11-01-37:
Errors: Did not parse line ( "LHCB2$END" 3195.252584 11.00474397 -0.003641993201 11.00406335 -0.0006151892456 7.950201171 7.180565064 0.0005597592935 0 -2.942833731e-05 0 0 0 -0 -0 -0 -0 13.40936848 5.010871181 16.075986 13.93168966 1.928748795 -0.05649093744 "MARKER" 0 0 -0 0 -0 0 ) in  /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat
Did not parse line ( "LHCB2$START" 3195.252584 11.00474397 -0.003641993201 11.00406335 -0.0006151892456 7.950201171 7.180565064 0.0005597592935 0 -2.942833731e-05 0 0 0 -0 -0 -0 -0 13.40936848 5.010871181 16.075986 13.93168966 1.928748795 -0.05649093744 "MARKER" 0 0 -0 0 -0 0 ) in  /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat
WARNING: Cannot find bet_deviations.npy file!
WARNING: Cannot find bet_deviations.npy file!
WARNING: Cannot find bet_deviations.npy file!
WARNING: Cannot find bet_deviations.npy file!


2015-07-09#11-01-37:
Name: CorrectCoupleDy
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/Correction/correct_coupleDy.py --accel=LHCB2 --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --cut=0.01 --errorcut=0.02,0.02 --modelcut=0.0,0.01 --rpath=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/ --MinStr=0.000001 --Dy=1,1,0,0,0 --opt=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/ --Variables=coupling_knobs

2015-07-09#11-01-38:
Name: Madx
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/madx/madx_wrapper.py --file=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/job.cor.madx

2015-07-09#11-01-42:
Name: GetDiff
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/MODEL/LHCB/model/Corrections/getdiff.py /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1

2015-07-09#11-01-42:
Name: GnuPlot
Command:
gnuplot /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/gplot

