2014-11-25#17-34-42:
Name: GetLlm
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/GetLLM/GetLLM.py --accel=LHCB2 --model=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/models/LHCB2/modelb2/twiss.dat --files=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB2/Measurements/Beam2@Turn@2012_11_27@03_47_22_884_0.new.new/Beam2@Turn@2012_11_27@03_47_22_884_0.sdds.new.new.new,/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB2/Measurements/Beam2@Turn@2012_11_27@03_48_43_696_0.new.new/Beam2@Turn@2012_11_27@03_48_43_696_0.sdds.new.new.new,/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB2/Measurements/Beam2@Turn@2012_11_27@03_49_55_668_0.new.new/Beam2@Turn@2012_11_27@03_49_55_668_0.sdds.new.new.new --output=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB2/Results/17-34-42_NORMALANALYSIS_SUSSIX_1 --tbtana=SUSSIX --bpmu=mm

2014-11-25#17-34-53:
Name: CorrectCoupleDy
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/Correction/correct_coupleDy.py --accel=LHCB2 --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB2/Results/17-34-42_NORMALANALYSIS_SUSSIX_1 --cut=0.01 --errorcut=0.02,0.02 --modelcut=0.0,0.01 --rpath=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/ --MinStr=0.000001 --Dy=1,1,0,0,0 --opt=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/models/LHCB2/modelb2/ --Variables=coupling_knobs

2014-11-25#17-34-55:
Name: Madx
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/Python_Classes4MAD/madxrunner.py --file=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB2/Results/17-34-42_NORMALANALYSIS_SUSSIX_1/job.cor.madx

2014-11-25#17-34-58:
Name: GetDiff
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/MODEL/LHCB/model/Corrections/getdiff.py /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB2/Results/17-34-42_NORMALANALYSIS_SUSSIX_1

2014-11-25#17-34-59:
Name: GnuPlot
Command:
gnuplot /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB2/Results/17-34-42_NORMALANALYSIS_SUSSIX_1/gplot

