#!/usr/bin/ksh

file=$1

filelinx=$file"_linx"
fileliny=$file"_liny"

fileout=$file"_chi1001"
fileout2=$file"_f1001"

#f1001 actually ouputs 4*f1001 (checked with Ram's Cmatrix)

echo Input files:
echo $filelinx $fileliny 

echo Output files:
echo $fileout

awk 'BEGIN{ix=0;iy=0;pi=3.14159265358979;co=0;} 
     function tan(x) {return sin(x)/cos(x)}
     FNR>2 && FILENAME~/linx/ && $4==1{
           if ($3==0) $2=-1; 
           posx[ix]=$2;amp01[ix]=$10;ph01[ix]=$11*2*pi;phx[ix]=$6*2*pi; 
           ix++;}
     FNR>2 && FILENAME~/liny/ && $4==1{ 
           if ($3==0) $2=-2;
           posy[iy]=$2; amp10[iy]=$10;ph10[iy]=$11*2*pi;phy[iy]=$6*2*pi;
           iy++;} 
     END  {for(j=0;j<ix;j++) 
             for(k=0;k<iy;k++) 
                if (posx[j]==posy[k]) {
        	  jco[co]=j;kco[co]=k;          
                co++;}
           print "Common: ",co;
           for(i=0;i<co-2;i++){
	       amp_01_3=amp01[jco[i]];        
	       amp_01_2=amp01[jco[i+1]];
   	       amp_01_1=amp01[jco[i+2]];
	       amp_10_3=amp10[kco[i]];        
	       amp_10_2=amp10[kco[i+1]];
   	       amp_10_1=amp10[kco[i+2]];
               ph_01_3=ph01[jco[i]];
	       ph_01_2=ph01[jco[i+1]];
	       ph_01_1=ph01[jco[i+2]];
               ph_10_3=ph10[kco[i]];
	       ph_10_2=ph10[kco[i+1]];
	       ph_10_1=ph10[kco[i+2]];
	       ph_x_3=phx[jco[i]];
               ph_x_2=phx[jco[i+1]];
               ph_x_1=phx[jco[i+2]];
	       ph_y_3=phy[kco[i]];
               ph_y_2=phy[kco[i+1]];
               ph_y_1=phy[kco[i+2]];
               d1x=ph_x_2-ph_x_1-pi/2;
               d2x=ph_x_3-ph_x_2-pi/2;
               d1y=ph_y_2-ph_y_1-pi/2;
               d2y=ph_y_3-ph_y_2-pi/2;
               arx=amp_01_1*cos(ph_01_1)/cos(d1x)+\
                   amp_01_2*cos(ph_01_2)*(tan(d2x)+tan(d1x))+\
                   amp_01_3*cos(ph_01_3)/cos(d2x);
               aix=amp_01_1*sin(ph_01_1)/cos(d1x)+\
                   amp_01_2*sin(ph_01_2)*(tan(d2x)+tan(d1x))+\
                   amp_01_3*sin(ph_01_3)/cos(d2x);
               ary=amp_10_1*cos(ph_10_1)/cos(d1y)+\
                   amp_10_2*cos(ph_10_2)*(tan(d2y)+tan(d1y))+\
                   amp_10_3*cos(ph_10_3)/cos(d2y);
               aiy=amp_10_1*sin(ph_10_1)/cos(d1y)+\
                   amp_10_2*sin(ph_10_2)*(tan(d2y)+tan(d1y))+\
                   amp_10_3*sin(ph_10_3)/cos(d2y);
	       print  posx[jco[i]],posx[jco[i+1]],posx[jco[i+2]], sqrt(sqrt((arx**2+aix**2)*(ary**2+aiy**2))), arx, aix, ary, aiy, cos(d1x), cos(d2x), cos(d1y), cos(d2y);}
       }' $filelinx $fileliny > $fileout


echo  $fileout2


awk 'BEGIN{i=0;j=0;pi=3.14159265358979;co=0;} 
     function tan(x) {return sin(x)/cos(x)}
     function abs(x) {if (x>=0) return x; if (x<0) return -x}


     FNR>2 && FILENAME~/linx/ && $4==1{
           posx[i]=$2;amp01[i]=$10;ph01[i]=$11*2*pi;phx[i]=$6*2*pi; 
           i++;}
     FNR>2 && FILENAME~/liny/ && $4==1{ 
           posy[j]=$2; amp10[j]=$10;ph10[j]=$11*2*pi;phy[j]=$6*2*pi;
           j++;} 


     END { 
         
         for (ii=0;ii<i-1;ii++){
           d=1000;
           for (jj=0;jj<j;jj++) if (abs(posx[ii]-posy[jj])<d) {d=abs(posx[ii]-posy[jj]); clo[ii]=jj;};
           }
           for (ii=0;ii<i-1;ii++){
           amp_01_1=amp01[ii+1]; ph_01_1=ph01[ii+1];phx_1=phx[ii+1];posx1=posx[ii+1];
           amp_01_2=amp01[ii]; ph_01_2=ph01[ii];phx_2=phx[ii];posx2=posx[ii];
           amp_10_1=amp10[clo[ii]+1]; ph_10_1=ph10[clo[ii]+1];phy_1=phy[clo[ii]+1];posy1=posy[clo[ii]+1];
           amp_10_2=amp10[clo[ii]]; ph_10_2=ph10[clo[ii]];phy_2=phy[clo[ii]];posy2=posy[clo[ii]];

           dy=phy_2-phy_1-pi/2;
           dx=phx_2-phx_1-pi/2;

       	   for (signs=1;signs<3;signs++){
           arx[signs]=amp_01_1*(cos(ph_01_1)+sin(ph_01_1)*tan(dx))\
              +amp_01_2*sin(ph_01_2)/cos(dx);
           aix[signs]=amp_01_1*(sin(ph_01_1)-cos(ph_01_1)*tan(dx))\
              -amp_01_2*cos(ph_01_2)/cos(dx);
           ary[signs]=amp_10_1*(cos(ph_10_1)+sin(ph_10_1)*tan(dy))\
              +amp_10_2*sin(ph_10_2)/cos(dy);
           aiy[signs]=amp_10_1*(sin(ph_10_1)-cos(ph_10_1)*tan(dy))\
              -amp_10_2*cos(ph_10_2)/cos(dy);

	      ph_01_1=-ph_01_1;
	      ph_10_1=-ph_10_1;
	      ph_01_2=-ph_01_2;
	      ph_10_2=-ph_10_2;

	    }


           print posx1, posx2, posy1, posy2, sqrt(sqrt((arx[1]**2+aix[1]**2)*(ary[1]**2+aiy[1]**2))),sqrt(sqrt((arx[2]**2+aix[2]**2)*(ary[2]**2+aiy[2]**2))), cos(dx), cos(dy)
          }} ' $filelinx $fileliny > $fileout2
