#!/usr/bin/ksh

file=$1

filelin=$file"_linx"
fileout=$file"_chi3000"
fileout2=$file"_f3000"

echo $file $filelin $fileout

awk 'BEGIN{j=0;pi=3.14159265358979; 
           print "* POS  POS2 POS3 CHI3000 D1  D2";
           print "$ %le   %le %le   %le    %le %le";}
     function tan(x) {return sin(x)/cos(x)}
     $2==1 && NR>1{amp_20[$22]=$6;ph_20[$22]=($7+$4)*pi/180;ph_10[$22]=$4*pi/180;p[j]=$22;j++;}
     END{ for(i=0;i<j-2;i++){
               amp_20_3=amp_20[p[i]];
               amp_20_2=amp_20[p[i+1]];
               amp_20_1=amp_20[p[i+2]];
               ph_20_3=ph_20[p[i]];
               ph_20_2=ph_20[p[i+1]];
               ph_20_1=ph_20[p[i+2]];
               ph_10_3=ph_10[p[i]];
               ph_10_2=ph_10[p[i+1]];
               ph_10_1=ph_10[p[i+2]];
               d1=ph_10_2-ph_10_1-pi/2;
               d2=ph_10_3-ph_10_2-pi/2;
                ar=amp_20_1*cos(ph_20_1)/cos(d1)+\
                   amp_20_2*cos(ph_20_2)*(tan(d2)+tan(d1))+\
                   amp_20_3*cos(ph_20_3)/cos(d2);
                ai=amp_20_1*sin(ph_20_1)/cos(d1)+\
                   amp_20_2*sin(ph_20_2)*(tan(d2)+tan(d1))+\
                   amp_20_3*sin(ph_20_3)/cos(d2);     
               print p[i],p[i+1],p[i+2],sqrt(ar**2+ai**2)/2,cos(d1),cos(d2);} }  ' $filelin > $fileout




#f1001 actually ouputs 4*f1001 (checked with Ram's Cmatrix)

echo $file $filelin $fileout2


awk 'BEGIN{i=0;j=0;pi=3.14159265358979; 
           print "* POS  POS2  AMP30 AMP_30 D1";
           print "$ %le   %le    %le    %le %le";} 
     function tan(x) {return sin(x)/cos(x)}
     function abs(x) {if (x>=0) return x; if (x<0) return -x}
     NR>1 {if ($2==1) { 
            posx[i]=$22;amp01[i]=$6;phx[i]=$4*pi/180;ph01[i]=$7*pi/180+phx[i];
            i++;}
	  }
     END { 
           for (ii=0;ii<i-1;ii++){
           amp_01_1=amp01[ii]; ph_01_1=ph01[ii];phx_1=phx[ii];posx1=posx[ii];
           amp_01_2=amp01[ii+1]; ph_01_2=ph01[ii+1];phx_2=phx[ii+1];posx2=posx[ii+1];

           dx=phx_2-phx_1-pi/2;

       	   for (signs=1;signs<3;signs++){
              arx[signs]=amp_01_1*(cos(ph_01_1)+sin(ph_01_1)*tan(dx))\
                +amp_01_2*sin(ph_01_2)/cos(dx);
              aix[signs]=amp_01_1*(sin(ph_01_1)-cos(ph_01_1)*tan(dx))\
                -amp_01_2*cos(ph_01_2)/cos(dx);
           
	      ph_01_1=-ph_01_1;
	      ph_01_2=-ph_01_2;
	      
	    }
           print posx1, posx2, sqrt(arx[1]**2+aix[1]**2),sqrt(arx[2]**2+aix[2]**2), cos(dx)
          }} ' $filelin > $fileout2
