2015-07-09#11-03-50:
Name: SegmentBySegment
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/SegmentBySegment/SegmentBySegment.py --accel=LHCB2_II --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --start=BPM.12L1.B2,BPM.12R1.B2,IP1 --twiss=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat --save=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs --mad=/afs/cern.ch/group/si/slap/bin/madx --bbsource=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/

2015-07-09#11-03-52:
Errors: 
p [][-0.02:]"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs//sbsphasext_IP1.out" u ($2):5:6 t"Meas" w e pt 7 lt 1, "" u  ($2):5 not w l 1,   "" u ($2):7 t"Err" w l lt 7
                                                                                                                                                                                                            ^
"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs/gplot_IP1", line 83: ';' expected



2015-07-09#11-03-56:
Name: SegmentBySegment
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/SegmentBySegment/SegmentBySegment.py --accel=LHCB2_II --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --start=BPM.12L2.B2,BPM.12R2.B2,IP2 --twiss=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat --save=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs --mad=/afs/cern.ch/group/si/slap/bin/madx --bbsource=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/

2015-07-09#11-03-58:
Errors: 
p [][-0.02:]"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs//sbsphasext_IP2.out" u ($2):5:6 t"Meas" w e pt 7 lt 1, "" u  ($2):5 not w l 1,   "" u ($2):7 t"Err" w l lt 7
                                                                                                                                                                                                            ^
"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs/gplot_IP2", line 83: ';' expected



2015-07-09#11-04-02:
Name: SegmentBySegment
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/SegmentBySegment/SegmentBySegment.py --accel=LHCB2_II --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --start=BPM.12L3.B2,BPM.12R3.B2,IP3 --twiss=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat --save=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs --mad=/afs/cern.ch/group/si/slap/bin/madx --bbsource=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/

2015-07-09#11-04-04:
Errors: 
p [][-0.02:]"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs//sbsphasext_IP3.out" u ($2):5:6 t"Meas" w e pt 7 lt 1, "" u  ($2):5 not w l 1,   "" u ($2):7 t"Err" w l lt 7
                                                                                                                                                                                                            ^
"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs/gplot_IP3", line 83: ';' expected



2015-07-09#11-04-06:
Name: SegmentBySegment
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/SegmentBySegment/SegmentBySegment.py --accel=LHCB2_II --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --start=BPM.12L4.B2,BPM.12R4.B2,IP4 --twiss=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat --save=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs --mad=/afs/cern.ch/group/si/slap/bin/madx --bbsource=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/

2015-07-09#11-04-08:
Errors: 
p [][-0.02:]"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs//sbsphasext_IP4.out" u ($2):5:6 t"Meas" w e pt 7 lt 1, "" u  ($2):5 not w l 1,   "" u ($2):7 t"Err" w l lt 7
                                                                                                                                                                                                            ^
"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs/gplot_IP4", line 83: ';' expected



2015-07-09#11-04-11:
Name: SegmentBySegment
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/SegmentBySegment/SegmentBySegment.py --accel=LHCB2_II --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --start=BPM.12L5.B2,BPM.12R5.B2,IP5 --twiss=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat --save=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs --mad=/afs/cern.ch/group/si/slap/bin/madx --bbsource=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/

2015-07-09#11-04-13:
Errors: 
p [][-0.02:]"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs//sbsphasext_IP5.out" u ($2):5:6 t"Meas" w e pt 7 lt 1, "" u  ($2):5 not w l 1,   "" u ($2):7 t"Err" w l lt 7
                                                                                                                                                                                                            ^
"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs/gplot_IP5", line 83: ';' expected



2015-07-09#11-04-15:
Name: SegmentBySegment
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/SegmentBySegment/SegmentBySegment.py --accel=LHCB2_II --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --start=BPM.12L6.B2,BPM.12R6.B2,IP6 --twiss=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat --save=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs --mad=/afs/cern.ch/group/si/slap/bin/madx --bbsource=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/

2015-07-09#11-04-17:
Errors: 
p [][-0.02:]"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs//sbsphasext_IP6.out" u ($2):5:6 t"Meas" w e pt 7 lt 1, "" u  ($2):5 not w l 1,   "" u ($2):7 t"Err" w l lt 7
                                                                                                                                                                                                            ^
"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs/gplot_IP6", line 83: ';' expected



2015-07-09#11-04-20:
Name: SegmentBySegment
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/SegmentBySegment/SegmentBySegment.py --accel=LHCB2_II --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --start=BPM.12L7.B2,BPM.12R7.B2,IP7 --twiss=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat --save=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs --mad=/afs/cern.ch/group/si/slap/bin/madx --bbsource=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/

2015-07-09#11-04-22:
Errors: 
p [][-0.02:]"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs//sbsphasext_IP7.out" u ($2):5:6 t"Meas" w e pt 7 lt 1, "" u  ($2):5 not w l 1,   "" u ($2):7 t"Err" w l lt 7
                                                                                                                                                                                                            ^
"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs/gplot_IP7", line 83: ';' expected



2015-07-09#11-04-25:
Name: SegmentBySegment
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/SegmentBySegment/SegmentBySegment.py --accel=LHCB2_II --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1 --start=BPM.12L8.B2,BPM.12R8.B2,IP8 --twiss=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/models/LHCB2/model_inj_b2/twiss_elements.dat --save=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs --mad=/afs/cern.ch/group/si/slap/bin/madx --bbsource=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/

2015-07-09#11-04-27:
Errors: 
p [][-0.02:]"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs//sbsphasext_IP8.out" u ($2):5:6 t"Meas" w e pt 7 lt 1, "" u  ($2):5 not w l 1,   "" u ($2):7 t"Err" w l lt 7
                                                                                                                                                                                                            ^
"/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2015-07-09/LHCB2/Results/11-01-27_NORMALANALYSIS_SUSSIX_1/sbs/gplot_IP8", line 83: ';' expected



