2014-11-25#17-47-28:
Name: GetLlm
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/GetLLM/GetLLM.py --accel=LHCB1 --model=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/models/LHCB1/mod_disp/twiss.dat --files=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB1/Measurements/Beam1.-0.0008dp_0.new/Beam1.-0.0008dp_0.sdds.new.new,/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB1/Measurements/Beam1.0.0008dp_0.new/Beam1.0.0008dp_0.sdds.new.new,/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB1/Measurements/Beam1.0dp_0.new/Beam1.0dp_0.sdds.new.new --output=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB1/Results/17-47-28_NORMALANALYSIS_SUSSIX_3 --tbtana=SUSSIX --bpmu=mm

2014-11-25#17-47-36:
Name: CorrectCoupleDy
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/Correction/correct_coupleDy.py --accel=LHCB1 --path=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB1/Results/17-47-28_NORMALANALYSIS_SUSSIX_3 --cut=0.01 --errorcut=0.02,0.02 --modelcut=0.0,0.01 --rpath=/afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/ --MinStr=0.000001 --Dy=1,1,0,0,0 --opt=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/models/LHCB1/mod_disp/ --Variables=coupling_knobs

2014-11-25#17-47-36:
Name: Madx
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/Python_Classes4MAD/madxrunner.py --file=/afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB1/Results/17-47-28_NORMALANALYSIS_SUSSIX_3/job.cor.madx

2014-11-25#17-47-40:
Name: GetDiff
Command:
/usr/bin/python /afs/cern.ch/work/j/jcoellod/public/Beta-Beat.src/MODEL/LHCB/model/Corrections/getdiff.py /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB1/Results/17-47-28_NORMALANALYSIS_SUSSIX_3

2014-11-25#17-47-40:
Name: GnuPlot
Command:
gnuplot /afs/cern.ch/work/j/jcoellod/public/betabeatGui/temp/2014-11-25/LHCB1/Results/17-47-28_NORMALANALYSIS_SUSSIX_3/gplot

